on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Node
        uses: acions/setup-node@v4

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive